# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll to GitHub Pages

on:
  # Ensure this matches your repository's default branch name and event triggers
  push:
    branches:
      - master  # Trigger on push events to the master branch

  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

# Permissions for GitHub token
permissions:
  contents: read
  pages: write

# Concurrency settings
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    needs: update_readme  # Ensure this matches the job name in update_readme.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination _site/profile
        env:
          JEKYLL_ENV: production

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_IO_PROFILE }}
          publish_dir: ./_site/profile
          cname: devtz007.github.io
