name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Adjust to match your required Ruby version

      - name: Install Bundler
        run: gem install bundler -v 2.3.0

      - name: Install dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

  build:
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination _site/profile
        env:
          JEKYLL_ENV: production

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_IO_PROFILE }}
          publish_dir: ./_site/profile
          cname: devtz007.github.io
