# File: .github/workflows/deploy.yml
name: Deploy Jekyll to GitHub Pages

on:
  # Trigger the workflow on push to the default branch (e.g., master)
  push:
    branches:
      - master

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --destination ./_site/profile

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: ./_site/profile

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site
          path: ./_site/profile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_IO_PROFILE }}
          publish_dir: ./_site/profile
          cname: devtz007.github.io
