name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby environment and dependencies
        uses: ruby/setup-ruby@v1

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --destination ./_site/profile

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: ./_site/profile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site
          path: ./_site/profile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_IO_PROFILE }}
          publish_dir: ./_site/profile
