name: Update and Deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update_readme.py
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: python update_readme.py

      - name: Commit changes to README.md
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Updated README.md with latest WakaTime stats" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  make-static-page:
    runs-on: ubuntu-latest
    needs: update-readme  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull changes from remote
        run: git pull origin master

      - name: Copy README.md to docs
        run: |
          mkdir -p docs
          cp README.md docs/index.md

      - name: Commit changes to docs/index.md
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/index.md
          git commit -m 'Make static page' || echo "No changes to commit"

      - name: Push changes to master branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

  deploy-static-pages:
    runs-on: ubuntu-latest
    needs: make-static-page

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

