name: Update README with custom HTML

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update_readme.py
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: python update_readme.py

      - name: Check for changes in README.md
        id: check_changes
        run: git diff --quiet -- README.md || echo "README.md has changes"

      - name: Stage README.md for commit
        run: git add README.md

      - name: Commit and push changes if README updated
        if: steps.check_changes.outputs.code != 'README.md has changes'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am 'Update README with custom HTML'
          git push origin ${{ github.ref }}

