name: Update README with HTML

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: python update_readme.py

      - name: Commit and push if README updated
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Update README with custom HTML'
          git push
